In [ ]:
import numpy as np

# Python lists

## Common use case

In [ ]:
l = [1,2,3,4]

In [ ]:
# most common use case:

l = []
n = 100
for a in range(1, n):
  for b in range(a, n):
    for c in range(a, n):
      if a**2 + b**2 == c**2:
        l.append([a,b,c])

In [ ]:
len(l)

50

In [ ]:
len = 5

In [ ]:
l[:4]

[[3, 4, 5], [5, 12, 13], [6, 8, 10], [7, 24, 25]]

In [ ]:
list

[1, 2, 3]

In [ ]:
l2 = list("abcd")

TypeError: ignored

In [ ]:
l2

['a', 'b', 'c', 'd']

In [ ]:
#

## Interesting problem

In [ ]:
# typical error

In [ ]:
# x= list(np.random.randn(10**3))

In [ ]:
# x[0]

In [ ]:
list = [1,2,3]

In [ ]:
y= list(np.random.randn(10**3))

TypeError: ignored

In [ ]:
measument = [ [1, 2.5, "Adam"], [2, 3.5, "Klaudia"] ]

In [ ]:
measument[0][0] + measument[0][2]

TypeError: ignored

In [ ]:
0.1 + 0.2 == 0.3

False

# Numpy

## Numpy vs list

In [ ]:
def fun(x):
  return x**137 - x**2

In [ ]:
x1 = np.array([range(10)])

In [ ]:
fun(x1)

array([[                   0,                    0,                   -4,
         6390225231553133274,                  -16, -1527281209667402932,
                         -36,  1081395378516079382,                  -64,
         -904147318867942152]])

In [ ]:
x2 = np.geomspace(1e-5, 1e5, num=100)

In [ ]:
x2

array([1.00000000e-05, 1.26185688e-05, 1.59228279e-05, 2.00923300e-05,
       2.53536449e-05, 3.19926714e-05, 4.03701726e-05, 5.09413801e-05,
       6.42807312e-05, 8.11130831e-05, 1.02353102e-04, 1.29154967e-04,
       1.62975083e-04, 2.05651231e-04, 2.59502421e-04, 3.27454916e-04,
       4.13201240e-04, 5.21400829e-04, 6.57933225e-04, 8.30217568e-04,
       1.04761575e-03, 1.32194115e-03, 1.66810054e-03, 2.10490414e-03,
       2.65608778e-03, 3.35160265e-03, 4.22924287e-03, 5.33669923e-03,
       6.73415066e-03, 8.49753436e-03, 1.07226722e-02, 1.35304777e-02,
       1.70735265e-02, 2.15443469e-02, 2.71858824e-02, 3.43046929e-02,
       4.32876128e-02, 5.46227722e-02, 6.89261210e-02, 8.69749003e-02,
       1.09749877e-01, 1.38488637e-01, 1.74752840e-01, 2.20513074e-01,
       2.78255940e-01, 3.51119173e-01, 4.43062146e-01, 5.59081018e-01,
       7.05480231e-01, 8.90215085e-01, 1.12332403e+00, 1.41747416e+00,
       1.78864953e+00, 2.25701972e+00, 2.84803587e+00, 3.59381366e+00,
      

In [ ]:
cond = x2 > 1e-3

In [ ]:
x2[cond]

array([1.04761575e-03, 1.32194115e-03, 1.66810054e-03, 2.10490414e-03,
       2.65608778e-03, 3.35160265e-03, 4.22924287e-03, 5.33669923e-03,
       6.73415066e-03, 8.49753436e-03, 1.07226722e-02, 1.35304777e-02,
       1.70735265e-02, 2.15443469e-02, 2.71858824e-02, 3.43046929e-02,
       4.32876128e-02, 5.46227722e-02, 6.89261210e-02, 8.69749003e-02,
       1.09749877e-01, 1.38488637e-01, 1.74752840e-01, 2.20513074e-01,
       2.78255940e-01, 3.51119173e-01, 4.43062146e-01, 5.59081018e-01,
       7.05480231e-01, 8.90215085e-01, 1.12332403e+00, 1.41747416e+00,
       1.78864953e+00, 2.25701972e+00, 2.84803587e+00, 3.59381366e+00,
       4.53487851e+00, 5.72236766e+00, 7.22080902e+00, 9.11162756e+00,
       1.14975700e+01, 1.45082878e+01, 1.83073828e+01, 2.31012970e+01,
       2.91505306e+01, 3.67837977e+01, 4.64158883e+01, 5.85702082e+01,
       7.39072203e+01, 9.32603347e+01, 1.17681195e+02, 1.48496826e+02,
       1.87381742e+02, 2.36448941e+02, 2.98364724e+02, 3.76493581e+02,
      

In [ ]:
!pip install random-pesel 

In [ ]:
from random_pesel import RandomPESEL
pesel = RandomPESEL()

# Generate random PESEL number
pesel.generate()

'32040112137'

In [ ]:
# Generate random PESEL number
pesel.generate()

'74041830429'

In [ ]:
from tqdm import tqdm

In [ ]:
pesel_list = []
for _ in tqdm(range(10000000)):
  current_pesel = pesel.generate()
  pesel_list.append(int(current_pesel))

100%|██████████| 10000000/10000000 [03:04<00:00, 54075.78it/s]


In [ ]:
len(pesel_list)

10000000

In [ ]:
pesel_list[13]

87042623868

In [ ]:
pesel_list[13] % 1000

868

In [ ]:
pesel_list[13] % 1000 == 137

False

In [ ]:
%time filtered_list = [x for x in pesel_list if x % 1000 == 137]

CPU times: user 1.09 s, sys: 14 µs, total: 1.09 s
Wall time: 1.1 s


In [ ]:
len(filtered_list)

10110

In [ ]:
100 * len(filtered_list) / len(pesel_list)

0.1011

In [ ]:
pesel_ndarray = np.asarray(pesel_list)

In [ ]:
%time filtered_ndarray = pesel_ndarray[pesel_ndarray % 1000 == 137]

CPU times: user 136 ms, sys: 42.1 ms, total: 178 ms
Wall time: 181 ms


In [ ]:
len(filtered_ndarray)

10110

In [ ]:
%time x = np.random.randint(low=1, high=100000, size=10000000)

CPU times: user 111 ms, sys: 0 ns, total: 111 ms
Wall time: 113 ms


In [ ]:
n = 40000000
year = np.random.randint(low=00, high=99, size=n)
month = np.random.randint(low=1, high=12, size=n)
day = np.random.randint(low=1, high=30, size=n)
ser_1 = np.random.randint(low=0, high=9, size=n)
ser_2 = np.random.randint(low=0, high=9, size=n)
ser_3 = np.random.randint(low=0, high=9, size=n)
sex = np.random.randint(low=0, high=1, size=n)

day[month == 1] = np.random.randint(low=1, high=31, size=n)

# checksum
control = (year//10) + 3*(year%10)
control += 7*(month//10) + 9*(month%10)
control += (day//10) + 3*(day%10)
control += 7*(ser_1//10) + 9*(ser_1%10)
control += (ser_2//10) + 3*(ser_2%10)
control += 7*(ser_3//10) + 9*(ser_3%10)
control += (sex//10) + 3*(sex%10)

control = (10 - (control % 10)) % 10

pesel_db = 1000000000*year + 10000000*month + 100000*day + 10000*ser_1 + 1000*ser_2 + 100*ser_3 + 10 * sex + control

In [ ]:
pesel_db[1]

78080400409

In [ ]:
%time filtered_ndarray = pesel_db[pesel_db % 1000 == 137]

CPU times: user 530 ms, sys: 1.94 ms, total: 532 ms
Wall time: 534 ms


In [ ]:
pesel_list2 = pesel_db.tolist()

In [ ]:
%time filtered_list = [x for x in pesel_list2 if x % 1000 == 137]

CPU times: user 4.21 s, sys: 1.73 ms, total: 4.22 s
Wall time: 4.22 s


In [ ]:
pesel_db.nbytes // 1000000

320

In [ ]:
%time res = np.unique(pesel_db, return_counts=True)

CPU times: user 5.69 s, sys: 227 ms, total: 5.92 s
Wall time: 5.93 s


In [ ]:
res

(array([   10100008,    10100109,    10100200, ..., 98112988602,
        98112988703, 98112988804]), array([2, 1, 5, ..., 1, 3, 1]))